apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: word-generator
  labels:
    app: word-generator
    component: cache
    technology: redis
  annotations:
    description: "Redis cluster configuration for word generator application caching"
data:
  redis.conf: |
    # Network configuration
    port 6379
    bind 0.0.0.0
    protected-mode no
    tcp-keepalive 300
    timeout 0

    # Cluster configuration
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000

    # Persistence configuration
    appendonly yes
    appendfsync everysec
    no-appendfsync-on-rewrite yes
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # RDB persistence
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    # Memory management
    maxmemory 3gb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5
    replica-ignore-maxmemory yes

    # Security
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""

    # Performance tuning
    activerehashing yes
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    replica-lazy-flush yes

    # Slow log configuration
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Latency monitoring
    latency-monitor-threshold 100

    # Client configuration
    maxclients 10000

    # IOs configuration
    aof-rewrite-incremental-fsync yes
    aof-load-truncated yes
    
    # Defrag configuration
    activedefrag yes
    active-defrag-ignore-bytes 100mb
    active-defrag-threshold-lower 10
    active-defrag-threshold-upper 100
    active-defrag-cycle-min 25
    active-defrag-cycle-max 75

    # Logging configuration
    loglevel notice
    logfile ""