apiVersion: v1
kind: Secret
metadata:
  name: word-generator-secrets
  namespace: default
  labels:
    app: word-generator
    component: secrets
    managed-by: terraform
  annotations:
    # Enable envelope encryption for at-rest data protection
    encryption.kubernetes.io/mode: "aes-256"
    # Rotate secrets every 90 days per security requirements
    rotation.kubernetes.io/schedule: "90d"
    # Enable audit logging for secret access
    audit.kubernetes.io/mode: "enabled"
type: Opaque
data:
  # Database credentials with secure connection parameters
  DATABASE_CREDENTIALS: |
    {
      "POSTGRES_USER": "d29yZF9nZW5lcmF0b3JfYXBw", # base64 encoded
      "POSTGRES_PASSWORD": "c3VwZXJfc2VjcmV0X3Bhc3N3b3JkXzEyMw==", # base64 encoded
      "POSTGRES_DB": "word_generator",
      "POSTGRES_HOST": "postgres-primary.default.svc.cluster.local",
      "POSTGRES_PORT": "5432",
      "POSTGRES_SSL": "true",
      "POSTGRES_SSL_MODE": "verify-full",
      "POSTGRES_SSL_CA": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...", # base64 encoded CA cert
      "POSTGRES_SSL_KEY": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...", # base64 encoded private key
      "POSTGRES_SSL_CERT": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t..." # base64 encoded client cert
    }

  # Authentication secrets for Auth0 and JWT
  AUTH_SECRETS: |
    {
      "AUTH0_DOMAIN": "d29yZC1nZW5lcmF0b3IuYXV0aDAuY29t", # base64 encoded
      "AUTH0_CLIENT_ID": "ZGpkODNqZDgzamQ4M2pkazgzamQ4M2pr", # base64 encoded
      "AUTH0_CLIENT_SECRET": "c3VwZXJfc2VjcmV0X2F1dGgwX2NsaWVudF9zZWNyZXRfMTIz", # base64 encoded
      "AUTH0_AUDIENCE": "aHR0cHM6Ly93b3JkLWdlbmVyYXRvci1hcGkuY29t", # base64 encoded
      "AUTH0_SCOPES": "openid profile email",
      "JWT_SECRET": "c3VwZXJfc2VjcmV0X2p3dF9zZWNyZXRfMTIz", # base64 encoded
      "JWT_EXPIRATION": "3600",
      "JWT_REFRESH_SECRET": "c3VwZXJfc2VjcmV0X2p3dF9yZWZyZXNoX3NlY3JldF8xMjM=", # base64 encoded
      "JWT_REFRESH_EXPIRATION": "86400"
    }

  # External API keys for third-party services
  API_KEYS: |
    {
      "OXFORD_DICTIONARY_API_KEY": "c3VwZXJfc2VjcmV0X294Zm9yZF9hcGlfa2V5", # base64 encoded
      "OXFORD_DICTIONARY_APP_ID": "d29yZF9nZW5lcmF0b3JfYXBw", # base64 encoded
      "DATADOG_API_KEY": "c3VwZXJfc2VjcmV0X2RhdGFkb2dfYXBpX2tleQ==", # base64 encoded
      "DATADOG_APP_KEY": "c3VwZXJfc2VjcmV0X2RhdGFkb2dfYXBwX2tleQ==", # base64 encoded
      "SENTRY_DSN": "aHR0cHM6Ly94eHh4QHNlbnRyeS5pby94eHh4", # base64 encoded
      "SENTRY_ENVIRONMENT": "production"
    }

  # Redis cache credentials and configuration
  REDIS_CREDENTIALS: |
    {
      "REDIS_PASSWORD": "c3VwZXJfc2VjcmV0X3JlZGlzX3Bhc3N3b3Jk", # base64 encoded
      "REDIS_TLS_ENABLED": "true",
      "REDIS_TLS_KEY": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...", # base64 encoded private key
      "REDIS_TLS_CERT": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...", # base64 encoded client cert
      "REDIS_TLS_CA": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...", # base64 encoded CA cert
      "REDIS_ACL_RULES": "allcommands allkeys",
      "REDIS_MAX_MEMORY": "2gb",
      "REDIS_MAX_MEMORY_POLICY": "allkeys-lru"
    }