# Kubernetes storage configuration for Random Word Generator application
# Version: 1.0.0
# Supports Redis cache and PostgreSQL database storage requirements
# Implements high-availability and data persistence with AWS EBS volumes

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app: word-generator
    environment: production
    managed-by: terraform
  annotations:
    description: "Production storage class for Random Word Generator application"
spec:
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp3
    iopsPerGB: "3000"
    fsType: ext4
    encrypted: "true"
  reclaimPolicy: Retain
  allowVolumeExpansion: true
  volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: word-generator
    component: cache
    storage: redis
    environment: production
  annotations:
    description: "Persistent volume for Redis cache storage"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    encrypted: true
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1a
                - us-east-1b
                - us-east-1c

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: word-generator
    component: database
    storage: postgresql
    environment: production
  annotations:
    description: "Persistent volume for PostgreSQL database storage"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    encrypted: true
    iopsPerGB: "3000"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1a
                - us-east-1b
                - us-east-1c

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: word-generator
  labels:
    app: word-generator
    component: cache
    storage: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: word-generator
  labels:
    app: word-generator
    component: database
    storage: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard