version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        NODE_VERSION: '18-alpine'
        TYPESCRIPT_VERSION: '5.0'
    container_name: word-generator-web
    restart: unless-stopped
    ports:
      - "5173:5173"  # Vite dev server
      - "9229:9229"  # Node.js debugging
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
      - VITE_API_VERSION=v1
      - VITE_ENVIRONMENT=development
      - NODE_ENV=development
      - DEBUG=word-generator:*
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - word-generator-network
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: '1.0'
        reservations:
          memory: 512MB
          cpus: '0.5'

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: /docker/volumes/node_modules
      o: bind

networks:
  word-generator-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: word-generator-dev
      com.docker.network.bridge.enable_icc: 'true'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16